name: Publish Helm Chart

on:
  repository_dispatch:
    types: [publish-helm]

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Publish chart to GitHub Pages
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
